// <auto-generated />
using System;
using System.Collections.Generic;
using DiscordHackWeek.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DiscordHackWeek.Migrations
{
    [DbContext(typeof(DbService))]
    [Migration("20190628075857_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DiscordHackWeek.Services.Database.Tables.Continent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("ImageSrc");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Continents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cairian Kingdom"
                        },
                        new
                        {
                            Id = 2,
                            Name = "The Frenzied Country"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ethereal Rift"
                        });
                });

            modelBuilder.Entity("DiscordHackWeek.Services.Database.Tables.Dungeon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("RequiredLevel");

                    b.HasKey("Id");

                    b.ToTable("Dungeons");
                });

            modelBuilder.Entity("DiscordHackWeek.Services.Database.Tables.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ArmorId");

                    b.Property<int>("Credit");

                    b.Property<int>("Exp");

                    b.Property<string>("HeavyAttack");

                    b.Property<string>("Image");

                    b.Property<string>("LightAttack");

                    b.Property<int[]>("LootTableIds");

                    b.Property<string>("Name");

                    b.Property<int>("RareDropChance");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<int?>("WeaponId");

                    b.Property<int>("ZoneId");

                    b.HasKey("Id");

                    b.ToTable("Enemies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credit = 0,
                            Exp = 20,
                            Image = "",
                            LootTableIds = new[] { 13 },
                            Name = "Bear",
                            RareDropChance = 1,
                            Type = "Beast",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            Credit = 0,
                            Exp = 20,
                            Image = "",
                            LootTableIds = new[] { 11 },
                            Name = "Boar",
                            RareDropChance = 1,
                            Type = "Beast",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 3,
                            Credit = 0,
                            Exp = 20,
                            Image = "",
                            LootTableIds = new[] { 10 },
                            Name = "Spider",
                            RareDropChance = 1,
                            Type = "Beast",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 4,
                            Credit = 0,
                            Exp = 20,
                            Image = "",
                            LootTableIds = new[] { 12 },
                            Name = "Wolf",
                            RareDropChance = 1,
                            Type = "Beast",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 5,
                            ArmorId = 1,
                            Credit = 5,
                            Exp = 30,
                            Image = "",
                            LootTableIds = new[] { 14, 15 },
                            Name = "Pirate",
                            RareDropChance = 1,
                            Type = "Humanoid",
                            WeaponId = 1,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 6,
                            Credit = 0,
                            Exp = 20,
                            Image = "",
                            LootTableIds = new[] { 13 },
                            Name = "Bear",
                            RareDropChance = 1,
                            Type = "Beast",
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 7,
                            Credit = 0,
                            Exp = 20,
                            Image = "",
                            LootTableIds = new[] { 11 },
                            Name = "Boar",
                            RareDropChance = 1,
                            Type = "Beast",
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 8,
                            Credit = 0,
                            Exp = 20,
                            Image = "",
                            LootTableIds = new[] { 10 },
                            Name = "Spider",
                            RareDropChance = 1,
                            Type = "Beast",
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 9,
                            Credit = 0,
                            Exp = 20,
                            Image = "",
                            LootTableIds = new[] { 12 },
                            Name = "Wolf",
                            RareDropChance = 1,
                            Type = "Beast",
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 10,
                            ArmorId = 1,
                            Credit = 5,
                            Exp = 50,
                            Image = "",
                            LootTableIds = new[] { 14, 15, 6, 7 },
                            Name = "Pirate",
                            RareDropChance = 1,
                            Type = "Humanoid",
                            WeaponId = 1,
                            ZoneId = 2
                        });
                });

            modelBuilder.Entity("DiscordHackWeek.Services.Database.Tables.GuildConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<List<string>>("Prefixes");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("DiscordHackWeek.Services.Database.Tables.IgnoreChannel", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<List<long>>("IgnoreList");

                    b.HasKey("GuildId");

                    b.ToTable("IgnoreChannels");
                });

            modelBuilder.Entity("DiscordHackWeek.Services.Database.Tables.Inventory", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<int>("ItemId");

                    b.Property<int>("Amount");

                    b.Property<string>("ItemType")
                        .IsRequired();

                    b.HasKey("UserId", "ItemId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("DiscordHackWeek.Services.Database.Tables.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CritIncrease");

                    b.Property<int>("DamageIncrease");

                    b.Property<int>("HealthIncrease");

                    b.Property<string>("ItemType")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<bool>("Unique");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CritIncrease = 10,
                            DamageIncrease = 10,
                            HealthIncrease = 0,
                            ItemType = "Weapon",
                            Name = "Regular Weapon",
                            Unique = false
                        },
                        new
                        {
                            Id = 2,
                            CritIncrease = 0,
                            DamageIncrease = 0,
                            HealthIncrease = 20,
                            ItemType = "Armor",
                            Name = "Regular Armor",
                            Unique = false
                        },
                        new
                        {
                            Id = 3,
                            CritIncrease = 0,
                            DamageIncrease = 0,
                            HealthIncrease = 20,
                            ItemType = "Food",
                            Name = "Bread",
                            Unique = false
                        },
                        new
                        {
                            Id = 4,
                            CritIncrease = 0,
                            DamageIncrease = 100,
                            HealthIncrease = 0,
                            ItemType = "Flask",
                            Name = "Damage Flask",
                            Unique = false
                        },
                        new
                        {
                            Id = 5,
                            CritIncrease = 0,
                            DamageIncrease = 0,
                            HealthIncrease = 30,
                            ItemType = "Potion",
                            Name = "Health Potion",
                            Unique = false
                        },
                        new
                        {
                            Id = 6,
                            CritIncrease = 5,
                            DamageIncrease = 20,
                            HealthIncrease = 0,
                            ItemType = "Weapon",
                            Name = "Iron Weapon",
                            Unique = false
                        },
                        new
                        {
                            Id = 7,
                            CritIncrease = 5,
                            DamageIncrease = 0,
                            HealthIncrease = 20,
                            ItemType = "Armor",
                            Name = "Iron Armor",
                            Unique = false
                        },
                        new
                        {
                            Id = 8,
                            CritIncrease = 20,
                            DamageIncrease = 30,
                            HealthIncrease = 0,
                            ItemType = "Weapon",
                            Name = "Steel Weapon",
                            Unique = false
                        },
                        new
                        {
                            Id = 9,
                            CritIncrease = 10,
                            DamageIncrease = 0,
                            HealthIncrease = 30,
                            ItemType = "Armor",
                            Name = "Steel Armor",
                            Unique = false
                        },
                        new
                        {
                            Id = 10,
                            CritIncrease = 0,
                            DamageIncrease = 0,
                            HealthIncrease = 0,
                            ItemType = "NoSpecial",
                            Name = "Spider Legs",
                            Unique = false
                        },
                        new
                        {
                            Id = 11,
                            CritIncrease = 0,
                            DamageIncrease = 0,
                            HealthIncrease = 0,
                            ItemType = "NoSpecial",
                            Name = "Boar Head",
                            Unique = false
                        },
                        new
                        {
                            Id = 12,
                            CritIncrease = 0,
                            DamageIncrease = 0,
                            HealthIncrease = 0,
                            ItemType = "NoSpecial",
                            Name = "Wolf Meat",
                            Unique = false
                        },
                        new
                        {
                            Id = 13,
                            CritIncrease = 0,
                            DamageIncrease = 0,
                            HealthIncrease = 0,
                            ItemType = "NoSpecial",
                            Name = "Bear Meat",
                            Unique = false
                        },
                        new
                        {
                            Id = 14,
                            CritIncrease = 0,
                            DamageIncrease = 0,
                            HealthIncrease = 0,
                            ItemType = "NoSpecial",
                            Name = "Broken Armor",
                            Unique = false
                        },
                        new
                        {
                            Id = 15,
                            CritIncrease = 0,
                            DamageIncrease = 0,
                            HealthIncrease = 0,
                            ItemType = "NoSpecial",
                            Name = "Wool Cloth",
                            Unique = false
                        });
                });

            modelBuilder.Entity("DiscordHackWeek.Services.Database.Tables.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArmorId");

                    b.Property<string>("AttackMode")
                        .IsRequired();

                    b.Property<int>("ContinentId");

                    b.Property<int>("Credit");

                    b.Property<int>("DamageTalent");

                    b.Property<int>("Exp");

                    b.Property<int>("HealthTalent");

                    b.Property<int>("Level");

                    b.Property<int>("TotalExp");

                    b.Property<int>("UnspentTalentPoints");

                    b.Property<int>("WeaponId");

                    b.Property<int>("ZoneId");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiscordHackWeek.Services.Database.Tables.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContinentId");

                    b.Property<string>("Description");

                    b.Property<int>("HighLevel");

                    b.Property<string>("ImageSrc");

                    b.Property<int>("LowLevel");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContinentId = 1,
                            Description = "",
                            HighLevel = 1,
                            ImageSrc = "",
                            LowLevel = 1,
                            Name = "Silver Willow Forest"
                        },
                        new
                        {
                            Id = 2,
                            ContinentId = 1,
                            Description = "",
                            HighLevel = 1,
                            ImageSrc = "",
                            LowLevel = 1,
                            Name = "Quiet Forest"
                        },
                        new
                        {
                            Id = 3,
                            ContinentId = 1,
                            Description = "",
                            HighLevel = 1,
                            ImageSrc = "",
                            LowLevel = 1,
                            Name = "Windy Hinterlands"
                        },
                        new
                        {
                            Id = 4,
                            ContinentId = 1,
                            Description = "",
                            HighLevel = 1,
                            ImageSrc = "",
                            LowLevel = 1,
                            Name = "The Eastern Tundra"
                        },
                        new
                        {
                            Id = 5,
                            ContinentId = 1,
                            Description = "",
                            HighLevel = 1,
                            ImageSrc = "",
                            LowLevel = 1,
                            Name = "Canomore Fjord"
                        },
                        new
                        {
                            Id = 6,
                            ContinentId = 1,
                            Description = "",
                            HighLevel = 1,
                            ImageSrc = "",
                            LowLevel = 1,
                            Name = "Wild Forest"
                        },
                        new
                        {
                            Id = 7,
                            ContinentId = 2,
                            Description = "",
                            HighLevel = 1,
                            ImageSrc = "",
                            LowLevel = 1,
                            Name = "Toxic Abyss"
                        },
                        new
                        {
                            Id = 8,
                            ContinentId = 2,
                            Description = "",
                            HighLevel = 1,
                            ImageSrc = "",
                            LowLevel = 1,
                            Name = "Forbidden Badlands"
                        },
                        new
                        {
                            Id = 9,
                            ContinentId = 2,
                            Description = "",
                            HighLevel = 1,
                            ImageSrc = "",
                            LowLevel = 1,
                            Name = "Raging Steppes"
                        },
                        new
                        {
                            Id = 10,
                            ContinentId = 2,
                            Description = "",
                            HighLevel = 1,
                            ImageSrc = "",
                            LowLevel = 1,
                            Name = "Angry Steppes"
                        },
                        new
                        {
                            Id = 11,
                            ContinentId = 3,
                            Description = "",
                            HighLevel = 1,
                            ImageSrc = "",
                            LowLevel = 1,
                            Name = "Phantom Lands"
                        },
                        new
                        {
                            Id = 12,
                            ContinentId = 3,
                            Description = "",
                            HighLevel = 1,
                            ImageSrc = "",
                            LowLevel = 1,
                            Name = "Shadow Lands"
                        },
                        new
                        {
                            Id = 13,
                            ContinentId = 3,
                            Description = "",
                            HighLevel = 1,
                            ImageSrc = "",
                            LowLevel = 1,
                            Name = "The Hidden Isles"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
